services:
    db:
        image: postgres
        volumes:
            - type: tmpfs
              target: /dev/shm
        environment:
            POSTGRES_PASSWORD: admin

    adminer:
        image: adminer
